[2025-04-08T15:16:18.694+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T15:16:18.719+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_the_api_history_per_day.write_the_new_api_history manual__2025-04-08T15:16:08.848818+00:00 [queued]>
[2025-04-08T15:16:18.733+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_the_api_history_per_day.write_the_new_api_history manual__2025-04-08T15:16:08.848818+00:00 [queued]>
[2025-04-08T15:16:18.734+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-08T15:16:18.924+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): write_the_new_api_history> on 2025-04-08 15:16:08.848818+00:00
[2025-04-08T15:16:18.935+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-08T15:16:18.936+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'monitor_the_api_history_per_day', 'write_the_new_api_history', 'manual__2025-04-08T15:16:08.848818+00:00', '--job-id', '481', '--raw', '--subdir', 'DAGS_FOLDER/monitor_the_api_history_per_day.py', '--cfg-path', '/tmp/tmphkjfzm98']
[2025-04-08T15:16:18.937+0000] {standard_task_runner.py:72} INFO - Started process 268 to run task
[2025-04-08T15:16:18.938+0000] {standard_task_runner.py:105} INFO - Job 481: Subtask write_the_new_api_history
[2025-04-08T15:16:19.010+0000] {task_command.py:467} INFO - Running <TaskInstance: monitor_the_api_history_per_day.write_the_new_api_history manual__2025-04-08T15:16:08.848818+00:00 [running]> on host c10f653d5b77
[2025-04-08T15:16:19.126+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Esayed' AIRFLOW_CTX_DAG_ID='monitor_the_api_history_per_day' AIRFLOW_CTX_TASK_ID='write_the_new_api_history' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T15:16:08.848818+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T15:16:08.848818+00:00'
[2025-04-08T15:16:19.128+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-08T15:16:19.129+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-08T15:16:19.130+0000] {logging_mixin.py:190} INFO - Current task name:write_the_new_api_history state:running start_date:2025-04-08 15:16:18.720213+00:00
[2025-04-08T15:16:19.131+0000] {logging_mixin.py:190} INFO - Dag name:monitor_the_api_history_per_day and current dag run status:running
[2025-04-08T15:16:19.131+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T15:16:19.248+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitor_the_api_history_per_day.py", line 97, in task_write_the_new_api_history
    write_the_new_api_history(api_from_less_than_or_equal_month)
  File "/opt/airflow/dags/monitor_the_api_history_per_day.py", line 73, in write_the_new_api_history
    api_from_less_than_or_equal_month.to_csv(api_history_file_path, mode='w', header=True, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: './files/API_History.csv'
[2025-04-08T15:16:19.291+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-08T15:16:19.292+0000] {logging_mixin.py:190} INFO - Task start:2025-04-08 15:16:18.720213+00:00 end:2025-04-08 15:16:19.291189+00:00 duration:0.570976
[2025-04-08T15:16:19.293+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): write_the_new_api_history> dag:<DAG: monitor_the_api_history_per_day> dagrun:<DagRun monitor_the_api_history_per_day @ 2025-04-08 15:16:08.848818+00:00: manual__2025-04-08T15:16:08.848818+00:00, state:running, queued_at: 2025-04-08 15:16:08.879766+00:00. externally triggered: True>
[2025-04-08T15:16:19.294+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 13] Permission denied: './files/API_History.csv'
[2025-04-08T15:16:19.294+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=monitor_the_api_history_per_day, task_id=write_the_new_api_history, run_id=manual__2025-04-08T15:16:08.848818+00:00, execution_date=20250408T151608, start_date=20250408T151618, end_date=20250408T151619
[2025-04-08T15:16:19.401+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T15:16:19.403+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 481 for task write_the_new_api_history ([Errno 13] Permission denied: './files/API_History.csv'; 268)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitor_the_api_history_per_day.py", line 97, in task_write_the_new_api_history
    write_the_new_api_history(api_from_less_than_or_equal_month)
  File "/opt/airflow/dags/monitor_the_api_history_per_day.py", line 73, in write_the_new_api_history
    api_from_less_than_or_equal_month.to_csv(api_history_file_path, mode='w', header=True, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: './files/API_History.csv'
[2025-04-08T15:16:19.435+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-08T15:16:19.461+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T15:16:19.464+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
